language: ruby
rvm:
- 2.1.0
before_script:
- cp config/database.sample.yml config/database.yml
- bundle exec rake db:migrate
env:
  global:
    secure: av4Q19rmcLb7ynBmTN6g+6gHLR7lESqbYT0jnRyKNKemrwBTDlZ1FKNWGzgB8vhXopoc8jJOP0TY8HG6ANhnrX9Th32FLjTkoRXD6UMYQ8kQfJrVPiMQIWbyeYr2MqB8rfHB1qVKW6HnXn0gi5BKR3ajpY0w0GtaCHNiO4yvFm8=
